"use client";

import Image from "next/image";
import { useState } from "react";

import { ArrowUpRightIcon } from "@/components/ui/Icon";
import { IMAGE_QUALITY } from "@/components/ui/image";
import bounds from "@/content/lebanon-map.json";
import type { Clinic } from "@/content/site";
import { contact } from "@/content/site";
import styles from "./ClinicLocator.module.css";

/**
 * All three clinics on one map, beside a card for each.
 *
 * The map is drawn rather than embedded: a Google iframe can only carry one pin without
 * an API key and a My Maps account, and three separate embeds — which is what this
 * replaced — made you compare three views to understand where anything was. Drawing it
 * also means the pins can talk to the cards. Directions still hand off to Google, which
 * is what people actually navigate with.
 *
 * The map is generated by scripts/lebanon-map.mjs, which is also where these bounds
 * come from.
 */

const W = bounds.cols * 10;
const H = bounds.rows * 10;

const px = (lng: number) =>
  ((lng - bounds.lonMin) / (bounds.lonMax - bounds.lonMin)) * W;
const py = (lat: number) =>
  ((bounds.latMax - lat) / (bounds.latMax - bounds.latMin)) * H;

export function ClinicLocator({ clinics }: { clinics: Clinic[] }) {
  const [active, setActive] = useState<string | null>(null);
  const pinned = clinics.filter((c) => c.coords);

  return (
    <div className={`${styles.root} ${active ? styles.focused : ""}`}>
      <div className={styles.mapPanel}>
        <figure className={styles.figure}>
          <svg
            className={styles.svg}
            viewBox={`0 0 ${W} ${H}`}
            role="img"
            aria-label={`Map of Lebanon showing ${pinned.map((c) => c.name).join(", ")}`}
          >
            {pinned.map((clinic) => {
              const x = px(clinic.coords!.lng);
              const y = py(clinic.coords!.lat);
              const on = active === clinic.name;
              return (
                <g
                  key={clinic.name}
                  className={`${styles.pin} ${on ? styles.pinOn : ""}`}
                  onMouseEnter={() => setActive(clinic.name)}
                  onMouseLeave={() => setActive(null)}
                >
                  {/* Halo doubles as a generous hit area for the pointer. */}
                  <circle className={styles.halo} cx={x} cy={y} r={34} />
                  <circle className={styles.dot} cx={x} cy={y} r={13} />
                </g>
              );
            })}
          </svg>

          {/*
            Labels are HTML positioned in percentages rather than SVG text: they stay a
            readable size however the map scales, and only the active one is shown —
            Jeita and Antelias are four kilometres apart, so at this scale their labels
            would otherwise sit on top of each other.
          */}
          {pinned.map((clinic) => (
            <span
              key={clinic.name}
              className={`${styles.tag} ${active === clinic.name ? styles.tagOn : ""}`}
              style={{
                left: `${(px(clinic.coords!.lng) / W) * 100}%`,
                top: `${(py(clinic.coords!.lat) / H) * 100}%`,
              }}
              aria-hidden="true"
            >
              {clinic.name.replace(/\s*Clinic\s*(—.*)?$/, "")}
            </span>
          ))}
        </figure>
      </div>

      <ul className={styles.list}>
        {clinics.map((clinic, i) => (
          <li key={clinic.name}>
            <article
              className={`${styles.card} ${active === clinic.name ? styles.cardOn : ""}`}
              onMouseEnter={() => setActive(clinic.name)}
              onMouseLeave={() => setActive(null)}
            >
              {clinic.image ? (
                <div className={styles.thumb}>
                  <Image
                    src={clinic.image}
                    alt={clinic.name}
                    fill
                    priority={i === 0}
                    sizes="220px"
                    className={styles.thumbImg}
                    quality={IMAGE_QUALITY}
                  />
                </div>
              ) : null}

              <div className={styles.body}>
                <h3 className={styles.name}>{clinic.name}</h3>
                <p className={styles.address}>{clinic.address}</p>
                <p className={styles.hours}>
                  {clinic.serviceTimes ?? (
                    <a href={contact.phoneHref}>Call {contact.phoneDisplay}</a>
                  )}
                </p>

                {clinic.directionsUrl ? (
                  <a
                    className={styles.directions}
                    href={clinic.directionsUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Get directions
                    <ArrowUpRightIcon width={13} height={13} />
                  </a>
                ) : null}
              </div>
            </article>
          </li>
        ))}
      </ul>
    </div>
  );
}
